chore: Restructure system to extract doc examples

diff --git a/.github/workflows/workspace-hack.yml b/.github/workflows/workspace-hack.yml
--- a/.github/workflows/workspace-hack.yml
+++ b/.github/workflows/workspace-hack.yml
@@ -24,7 +24,9 @@ jobs:
         uses: taiki-e/install-action@v2
         with:
           tool: cargo-hakari
-      - name: Verify workspace-hack
+      - name: Verify workspace-hack in libs/
+        id: verify_libs
+        continue-on-error: true
         run: |
           cd libs
           # If the hack crate has been disabled (probably for a release)
@@ -32,8 +34,28 @@ jobs:
           if ! cargo hakari disable --diff ; then
             # Check that px_workspace_hack's Cargo.toml is up-to-date
             # If this fails, run `cargo hakari generate` to fix it
-            cargo hakari generate --diff  
+            cargo hakari generate --diff
             # Check that all workspace crates depend on px_workspace_hack
             # If this fails, run `cargo hakari manage-deps` to fix it
             cargo hakari manage-deps --dry-run
           fi
+      - name: Verify workspace-hack in docs/examples
+        id: verify_examples
+        continue-on-error: true
+        run: |
+          cd docs/examples
+          # If the hack crate has been disabled (probably for a release)
+          # we don't check anything else
+          if ! cargo hakari disable --diff ; then
+            # Check that px_workspace_hack's Cargo.toml is up-to-date
+            # If this fails, run `cargo hakari generate` to fix it
+            cargo hakari generate --diff
+            # Check that all workspace crates depend on px_workspace_hack
+            # If this fails, run `cargo hakari manage-deps` to fix it
+            cargo hakari manage-deps --dry-run
+          fi
+      - name: Fail if any verification failed
+        if: steps.verify_libs.outcome == 'failure' || steps.verify_examples.outcome == 'failure'
+        run: |
+          echo "One or more verification steps failed. Check the logs of the previous steps for details."
+          exit 1
